/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elecciones;

/**
 *
 * @author crist
 */
public class Menu extends javax.swing.JFrame {

    Elecciones elecciones = new Elecciones();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputCandidatos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputMesas = new javax.swing.JTextField();
        ingresarResultadosBTN = new javax.swing.JButton();
        cantidadVotantesBTN = new javax.swing.JButton();
        candidatoMasVotadoBTN = new javax.swing.JButton();
        promedioVotosMesaBTN = new javax.swing.JButton();
        mesaMasVotada = new javax.swing.JButton();
        votosPorCandidatoBTN = new javax.swing.JButton();
        SiguenteBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escrutiño de elecciones");

        inputCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCandidatosActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de candidatos");

        jLabel3.setText("Numero de mesas");

        inputMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMesasActionPerformed(evt);
            }
        });

        ingresarResultadosBTN.setText("Ingresar Datos");
        ingresarResultadosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarResultadosBTNActionPerformed(evt);
            }
        });

        cantidadVotantesBTN.setText("Cantidad Votantes");
        cantidadVotantesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadVotantesBTNActionPerformed(evt);
            }
        });

        candidatoMasVotadoBTN.setText("Candidato mas votado");
        candidatoMasVotadoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatoMasVotadoBTNActionPerformed(evt);
            }
        });

        promedioVotosMesaBTN.setText("Promedio votos por mesa");
        promedioVotosMesaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioVotosMesaBTNActionPerformed(evt);
            }
        });

        mesaMasVotada.setText("Mesa mas votada");
        mesaMasVotada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaMasVotadaActionPerformed(evt);
            }
        });

        votosPorCandidatoBTN.setText("Votos por cada cadidato");
        votosPorCandidatoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votosPorCandidatoBTNActionPerformed(evt);
            }
        });

        SiguenteBTN.setText("Next page");
        SiguenteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguenteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(cantidadVotantesBTN)
                                                        .addGap(33, 33, 33))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(promedioVotosMesaBTN)
                                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mesaMasVotada, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(candidatoMasVotadoBTN, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(136, 136, 136)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SiguenteBTN))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(inputCandidatos,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                71,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(inputMesas,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                71,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(44, 44, 44)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(ingresarResultadosBTN)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(111, 111, 111)
                                                                .addComponent(votosPorCandidatoBTN)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(SiguenteBTN)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inputCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(inputMesas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ingresarResultadosBTN)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cantidadVotantesBTN)
                                        .addComponent(candidatoMasVotadoBTN))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(promedioVotosMesaBTN)
                                        .addComponent(mesaMasVotada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(votosPorCandidatoBTN)
                                .addContainerGap(19, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguenteBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SiguenteBTNActionPerformed

        Menu2 menu2 = new Menu2();

        menu2.show();

        dispose();
    }// GEN-LAST:event_SiguenteBTNActionPerformed

    private void promedioVotosMesaBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_promedioVotosMesaBTNActionPerformed
        elecciones.promedioVotosMesa();
    }// GEN-LAST:event_promedioVotosMesaBTNActionPerformed

    private void mesaMasVotadaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesaMasVotadaActionPerformed
        elecciones.mesaMasVotada();
    }// GEN-LAST:event_mesaMasVotadaActionPerformed

    private void cantidadVotantesBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cantidadVotantesBTNActionPerformed
        elecciones.cantidadVotantes();
    }// GEN-LAST:event_cantidadVotantesBTNActionPerformed

    private void candidatoMasVotadoBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_candidatoMasVotadoBTNActionPerformed
        elecciones.candidatoMasVotado();
    }// GEN-LAST:event_candidatoMasVotadoBTNActionPerformed

    private void votosPorCandidatoBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_votosPorCandidatoBTNActionPerformed
        elecciones.votosPorCadidato();
    }// GEN-LAST:event_votosPorCandidatoBTNActionPerformed

    private void inputCandidatosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputCandidatosActionPerformed

    }// GEN-LAST:event_inputCandidatosActionPerformed

    private void inputMesasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputMesasActionPerformed

    }// GEN-LAST:event_inputMesasActionPerformed

    private void ingresarResultadosBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ingresarResultadosBTNActionPerformed

        int nCandidatos = Integer.parseInt(inputCandidatos.getText());
        int nMesas = Integer.parseInt(inputMesas.getText());

        elecciones.crearArrays(nCandidatos, nMesas);
    }// GEN-LAST:event_ingresarResultadosBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SiguenteBTN;
    private javax.swing.JButton candidatoMasVotadoBTN;
    private javax.swing.JButton cantidadVotantesBTN;
    private javax.swing.JButton ingresarResultadosBTN;
    private javax.swing.JTextField inputCandidatos;
    private javax.swing.JTextField inputMesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mesaMasVotada;
    private javax.swing.JButton promedioVotosMesaBTN;
    private javax.swing.JButton votosPorCandidatoBTN;
    // End of variables declaration//GEN-END:variables
}
