package calculadora;

import com.sun.source.doctree.SummaryTree;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author crist
 */
public class VistaCalculadora extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(VistaCalculadora.class.getName());

    /**
     * Creates new form VistaCalculadora
     */
    public VistaCalculadora() {
        initComponents();
        BotonSumar.setVisible(false);
        BotonRestar.setVisible(false);
        BotonMultiplicar.setVisible(false);
        BotonDividir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        BotonSumar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        Num1Box = new javax.swing.JTextField();
        Num2Box = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonMultiplicar = new javax.swing.JButton();
        BotonRestar = new javax.swing.JButton();
        BotonDividir = new javax.swing.JButton();
        Calcular = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonSumar.setText("Sumar");
        BotonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumarActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenidos a mi Calculadora");

        Num1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1BoxActionPerformed(evt);
            }
        });

        Num2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2BoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero 1");

        jLabel3.setText("Numero 2");

        BotonMultiplicar.setText("Multiplicar");
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });

        BotonRestar.setText("Restar");
        BotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarActionPerformed(evt);
            }
        });

        BotonDividir.setText("Dividir");
        BotonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDividirActionPerformed(evt);
            }
        });

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Num1Box, javax.swing.GroupLayout.DEFAULT_SIZE, 71,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Num2Box, javax.swing.GroupLayout.DEFAULT_SIZE, 71,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(BotonSumar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BotonRestar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonMultiplicar)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonDividir))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(Calcular)))
                                .addContainerGap(24, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Num1Box, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Num2Box, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonSumar)
                                        .addComponent(BotonMultiplicar)
                                        .addComponent(BotonRestar)
                                        .addComponent(BotonDividir))
                                .addGap(125, 125, 125)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CalcularActionPerformed
        if (Num1Box.getText().equals("") || Num2Box.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "debe de rellenar los dos campos antes de ralizr una operacion");
        } else {

            BotonSumar.setVisible(true);
            BotonRestar.setVisible(true);
            BotonDividir.setVisible(true);
            BotonMultiplicar.setVisible(true);
            Calcular.setVisible(false);
        }

    }

    private void BotonRestarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonRestarActionPerformed

        try {
            CalculadoraLogica.restar(Double.parseDouble(Num1Box.getText()), Double.parseDouble(Num2Box.getText()));
            Num1Box.setText("");
            Num2Box.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No ingresar Letras o Espacios");
        }
        Calcular.setVisible(true);
        BotonSumar.setVisible(false);
        BotonRestar.setVisible(false);
        BotonMultiplicar.setVisible(false);
        BotonDividir.setVisible(false);

    }// GEN-LAST:event_BotonRestarActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonMultiplicarActionPerformed

        try {
            CalculadoraLogica.multplicar(Double.parseDouble(Num1Box.getText()), Double.parseDouble(Num2Box.getText()));
            Num1Box.setText("");
            Num2Box.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No ingresar Letras o Espacios");
        }
        Calcular.setVisible(true);
        BotonSumar.setVisible(false);
        BotonRestar.setVisible(false);
        BotonMultiplicar.setVisible(false);
        BotonDividir.setVisible(false);
    }// GEN-LAST:event_BotonMultiplicarActionPerformed

    private void BotonDividirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonDividirActionPerformed

        try {
            CalculadoraLogica.dividir(Double.parseDouble(Num1Box.getText()), Double.parseDouble(Num2Box.getText()));
            Num1Box.setText("");
            Num2Box.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No ingresar Letras o Espacios");
        }
        Calcular.setVisible(true);
        BotonSumar.setVisible(false);
        BotonRestar.setVisible(false);
        BotonMultiplicar.setVisible(false);
        BotonDividir.setVisible(false);
    }// GEN-LAST:event_BotonDividirActionPerformed

    private void Num1BoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Num1BoxActionPerformed

    }// GEN-LAST:event_Num1BoxActionPerformed

    private void Num2BoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Num2BoxActionPerformed

    }// GEN-LAST:event_Num2BoxActionPerformed

    private void BotonSumarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonSumarActionPerformed

        try {
            CalculadoraLogica.sumar(Double.parseDouble(Num1Box.getText()), Double.parseDouble(Num2Box.getText()));
            Num1Box.setText("");
            Num2Box.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No ingresar Letras o Espacios");
        }
        Calcular.setVisible(true);
        BotonSumar.setVisible(false);
        BotonRestar.setVisible(false);
        BotonMultiplicar.setVisible(false);
        BotonDividir.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDividir;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonRestar;
    private javax.swing.JToggleButton BotonSumar;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField Num1Box;
    private javax.swing.JTextField Num2Box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
